
CREATE TABLE IF NOT EXISTS `video` (
  `video_id` BIGINT(20) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `summary` VARCHAR(4096) DEFAULT '',
  `description` VARCHAR(4096) DEFAULT '',
  `level` TINYINT(2) DEFAULT '0',
  `file_size` BIGINT(20) DEFAULT '0',
  `video_time_length` BIGINT(20) DEFAULT '0',
  `video_width` TINYINT(11) DEFAULT '0',
  `video_height` TINYINT(11) DEFAULT '0',
  `video_data_rate` TINYINT(11) DEFAULT '0',
  `video_bit_rate` TINYINT(11) DEFAULT '0',
  `video_frame_rate` TINYINT(11) DEFAULT '0',
  `audio_bit_rate` TINYINT(11) DEFAULT '0',
  `audio_channel` TINYINT(11) DEFAULT '0',
  `audio_Sampling_rate` TINYINT(11) DEFAULT '0',
  `thumbnail` VARCHAR(256) DEFAULT '',
  `coding_type` VARCHAR(256) DEFAULT '',
  `compression_type` VARCHAR(256) DEFAULT '',
  `user_id` BIGINT(20) NOT NULL,
  `exp_name` VARCHAR(32) NOT NULL DEFAULT '',
  `html_url` VARCHAR(512) DEFAULT '',
  `artists` VARCHAR(512) DEFAULT '',
  `content_type` VARCHAR(32) DEFAULT '',
  `new_file_name` VARCHAR(128) DEFAULT '',
  `created_time` BIGINT(20) NOT NULL DEFAULT '0',
  `updated_time` BIGINT(20) NOT NULL DEFAULT '0',
  `destroyed_time` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`video_id`,`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8