/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.server.wutong.notif;
@SuppressWarnings("all")
public class Info extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Info\",\"namespace\":\"com.borqs.information.rpc.service\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"]},{\"name\":\"appId\",\"type\":\"string\"},{\"name\":\"senderId\",\"type\":\"string\"},{\"name\":\"receiverId\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"action\",\"type\":[\"null\",\"string\"]},{\"name\":\"uri\",\"type\":[\"null\",\"string\"]},{\"name\":\"title\",\"type\":[\"null\",\"string\"]},{\"name\":\"data\",\"type\":[\"null\",\"string\"]},{\"name\":\"processMethod\",\"type\":[\"null\",\"int\"]},{\"name\":\"importance\",\"type\":[\"null\",\"int\"]},{\"name\":\"guid\",\"type\":[\"null\",\"string\"]},{\"name\":\"body\",\"type\":[\"null\",\"string\"]},{\"name\":\"bodyHtml\",\"type\":[\"null\",\"string\"]},{\"name\":\"titleHtml\",\"type\":[\"null\",\"string\"]},{\"name\":\"cDateTime\",\"type\":[\"null\",\"long\"]},{\"name\":\"objectId\",\"type\":[\"null\",\"string\"]}]}");
  public Long id;
  public CharSequence appId;
  public CharSequence senderId;
  public CharSequence receiverId;
  public CharSequence type;
  public CharSequence action;
  public CharSequence uri;
  public CharSequence title;
  public CharSequence data;
  public Integer processMethod;
  public Integer importance;
  public CharSequence guid;
  public CharSequence body;
  public CharSequence bodyHtml;
  public CharSequence titleHtml;
  public Long cDateTime;
  public CharSequence objectId;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return appId;
    case 2: return senderId;
    case 3: return receiverId;
    case 4: return type;
    case 5: return action;
    case 6: return uri;
    case 7: return title;
    case 8: return data;
    case 9: return processMethod;
    case 10: return importance;
    case 11: return guid;
    case 12: return body;
    case 13: return bodyHtml;
    case 14: return titleHtml;
    case 15: return cDateTime;
    case 16: return objectId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (Long)value$; break;
    case 1: appId = (CharSequence)value$; break;
    case 2: senderId = (CharSequence)value$; break;
    case 3: receiverId = (CharSequence)value$; break;
    case 4: type = (CharSequence)value$; break;
    case 5: action = (CharSequence)value$; break;
    case 6: uri = (CharSequence)value$; break;
    case 7: title = (CharSequence)value$; break;
    case 8: data = (CharSequence)value$; break;
    case 9: processMethod = (Integer)value$; break;
    case 10: importance = (Integer)value$; break;
    case 11: guid = (CharSequence)value$; break;
    case 12: body = (CharSequence)value$; break;
    case 13: bodyHtml = (CharSequence)value$; break;
    case 14: titleHtml = (CharSequence)value$; break;
    case 15: cDateTime = (Long)value$; break;
    case 16: objectId = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
