/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.information.rpc.service;  
@SuppressWarnings("all")
public class Info extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Info\",\"namespace\":\"com.borqs.information.rpc.service\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"]},{\"name\":\"appId\",\"type\":\"string\"},{\"name\":\"senderId\",\"type\":\"string\"},{\"name\":\"receiverId\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"action\",\"type\":[\"null\",\"string\"]},{\"name\":\"uri\",\"type\":[\"null\",\"string\"]},{\"name\":\"title\",\"type\":[\"null\",\"string\"]},{\"name\":\"data\",\"type\":[\"null\",\"string\"]},{\"name\":\"processMethod\",\"type\":[\"null\",\"int\"]},{\"name\":\"importance\",\"type\":[\"null\",\"int\"]},{\"name\":\"guid\",\"type\":[\"null\",\"string\"]},{\"name\":\"body\",\"type\":[\"null\",\"string\"]},{\"name\":\"bodyHtml\",\"type\":[\"null\",\"string\"]},{\"name\":\"titleHtml\",\"type\":[\"null\",\"string\"]},{\"name\":\"cDateTime\",\"type\":[\"null\",\"long\"]},{\"name\":\"objectId\",\"type\":[\"null\",\"string\"]}]}");
  public java.lang.Long id;
  public java.lang.CharSequence appId;
  public java.lang.CharSequence senderId;
  public java.lang.CharSequence receiverId;
  public java.lang.CharSequence type;
  public java.lang.CharSequence action;
  public java.lang.CharSequence uri;
  public java.lang.CharSequence title;
  public java.lang.CharSequence data;
  public java.lang.Integer processMethod;
  public java.lang.Integer importance;
  public java.lang.CharSequence guid;
  public java.lang.CharSequence body;
  public java.lang.CharSequence bodyHtml;
  public java.lang.CharSequence titleHtml;
  public java.lang.Long cDateTime;
  public java.lang.CharSequence objectId;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return appId;
    case 2: return senderId;
    case 3: return receiverId;
    case 4: return type;
    case 5: return action;
    case 6: return uri;
    case 7: return title;
    case 8: return data;
    case 9: return processMethod;
    case 10: return importance;
    case 11: return guid;
    case 12: return body;
    case 13: return bodyHtml;
    case 14: return titleHtml;
    case 15: return cDateTime;
    case 16: return objectId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: appId = (java.lang.CharSequence)value$; break;
    case 2: senderId = (java.lang.CharSequence)value$; break;
    case 3: receiverId = (java.lang.CharSequence)value$; break;
    case 4: type = (java.lang.CharSequence)value$; break;
    case 5: action = (java.lang.CharSequence)value$; break;
    case 6: uri = (java.lang.CharSequence)value$; break;
    case 7: title = (java.lang.CharSequence)value$; break;
    case 8: data = (java.lang.CharSequence)value$; break;
    case 9: processMethod = (java.lang.Integer)value$; break;
    case 10: importance = (java.lang.Integer)value$; break;
    case 11: guid = (java.lang.CharSequence)value$; break;
    case 12: body = (java.lang.CharSequence)value$; break;
    case 13: bodyHtml = (java.lang.CharSequence)value$; break;
    case 14: titleHtml = (java.lang.CharSequence)value$; break;
    case 15: cDateTime = (java.lang.Long)value$; break;
    case 16: objectId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
