/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.information.rpc.service;  
@SuppressWarnings("all")
public class SendInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"SendInfo\",\"namespace\":\"com.borqs.information.rpc.service\",\"fields\":[{\"name\":\"appId\",\"type\":\"string\"},{\"name\":\"senderId\",\"type\":\"string\"},{\"name\":\"receiverId\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"uri\",\"type\":[\"null\",\"string\"]},{\"name\":\"title\",\"type\":[\"null\",\"string\"]},{\"name\":\"data\",\"type\":[\"null\",\"string\"]},{\"name\":\"processMethod\",\"type\":[\"null\",\"int\"]},{\"name\":\"importance\",\"type\":[\"null\",\"int\"]},{\"name\":\"body\",\"type\":[\"null\",\"string\"]},{\"name\":\"bodyHtml\",\"type\":[\"null\",\"string\"]},{\"name\":\"titleHtml\",\"type\":[\"null\",\"string\"]},{\"name\":\"objectId\",\"type\":[\"null\",\"string\"]},{\"name\":\"guid\",\"type\":[\"null\",\"string\"]},{\"name\":\"push\",\"type\":\"boolean\",\"default\":false},{\"name\":\"scene\",\"type\":[\"null\",\"string\"]},{\"name\":\"imageUrl\",\"type\":[\"null\",\"string\"]}]}");
  public java.lang.CharSequence appId;
  public java.lang.CharSequence senderId;
  public java.lang.CharSequence receiverId;
  public java.lang.CharSequence type;
  public java.lang.CharSequence uri;
  public java.lang.CharSequence title;
  public java.lang.CharSequence data;
  public java.lang.Integer processMethod;
  public java.lang.Integer importance;
  public java.lang.CharSequence body;
  public java.lang.CharSequence bodyHtml;
  public java.lang.CharSequence titleHtml;
  public java.lang.CharSequence objectId;
  public java.lang.CharSequence guid;
  public boolean push;
  public java.lang.CharSequence scene;
  public java.lang.CharSequence imageUrl;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return appId;
    case 1: return senderId;
    case 2: return receiverId;
    case 3: return type;
    case 4: return uri;
    case 5: return title;
    case 6: return data;
    case 7: return processMethod;
    case 8: return importance;
    case 9: return body;
    case 10: return bodyHtml;
    case 11: return titleHtml;
    case 12: return objectId;
    case 13: return guid;
    case 14: return push;
    case 15: return scene;
    case 16: return imageUrl;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: appId = (java.lang.CharSequence)value$; break;
    case 1: senderId = (java.lang.CharSequence)value$; break;
    case 2: receiverId = (java.lang.CharSequence)value$; break;
    case 3: type = (java.lang.CharSequence)value$; break;
    case 4: uri = (java.lang.CharSequence)value$; break;
    case 5: title = (java.lang.CharSequence)value$; break;
    case 6: data = (java.lang.CharSequence)value$; break;
    case 7: processMethod = (java.lang.Integer)value$; break;
    case 8: importance = (java.lang.Integer)value$; break;
    case 9: body = (java.lang.CharSequence)value$; break;
    case 10: bodyHtml = (java.lang.CharSequence)value$; break;
    case 11: titleHtml = (java.lang.CharSequence)value$; break;
    case 12: objectId = (java.lang.CharSequence)value$; break;
    case 13: guid = (java.lang.CharSequence)value$; break;
    case 14: push = (java.lang.Boolean)value$; break;
    case 15: scene = (java.lang.CharSequence)value$; break;
    case 16: imageUrl = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
