/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.server.service.platform;

@SuppressWarnings("all")
public interface Application {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Application\",\"namespace\":\"com.borqs.server.service.platform\",\"types\":[{\"type\":\"error\",\"name\":\"ResponseError\",\"namespace\":\"com.borqs.server.base\",\"fields\":[{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"getAppSecret\":{\"request\":[{\"name\":\"appId\",\"type\":\"string\"}],\"response\":\"string\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"findQiupuMinVersion\":{\"request\":[],\"response\":\"string\",\"errors\":[\"com.borqs.server.base.ResponseError\"]}}}");
  java.lang.CharSequence getAppSecret(java.lang.CharSequence appId) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.lang.CharSequence findQiupuMinVersion() throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;

  @SuppressWarnings("all")
  public interface Callback extends Application {
    public static final org.apache.avro.Protocol PROTOCOL = com.borqs.server.service.platform.Application.PROTOCOL;
    void getAppSecret(java.lang.CharSequence appId, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void findQiupuMinVersion(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}