/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.server.service.platform;

@SuppressWarnings("all")
public interface Ignore {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Ignore\",\"namespace\":\"com.borqs.server.service.platform\",\"types\":[{\"type\":\"error\",\"name\":\"ResponseError\",\"namespace\":\"com.borqs.server.base\",\"fields\":[{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"createIgnore\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"targetType\",\"type\":\"string\"},{\"name\":\"targetId\",\"type\":\"string\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"deleteIgnore\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"targetType\",\"type\":\"string\"},{\"name\":\"targetId\",\"type\":\"string\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getIgnoreList\":{\"request\":[{\"name\":\"user_id\",\"type\":\"string\"},{\"name\":\"target_type\",\"type\":\"string\"},{\"name\":\"page\",\"type\":\"int\"},{\"name\":\"count\",\"type\":\"int\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getExistsIgnore\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"targetType\",\"type\":\"string\"},{\"name\":\"targetId\",\"type\":\"string\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]}}}");
  boolean createIgnore(java.lang.CharSequence userId, java.lang.CharSequence targetType, java.lang.CharSequence targetId) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  boolean deleteIgnore(java.lang.CharSequence userId, java.lang.CharSequence targetType, java.lang.CharSequence targetId) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getIgnoreList(java.lang.CharSequence user_id, java.lang.CharSequence target_type, int page, int count) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  boolean getExistsIgnore(java.lang.CharSequence userId, java.lang.CharSequence targetType, java.lang.CharSequence targetId) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;

  @SuppressWarnings("all")
  public interface Callback extends Ignore {
    public static final org.apache.avro.Protocol PROTOCOL = com.borqs.server.service.platform.Ignore.PROTOCOL;
    void createIgnore(java.lang.CharSequence userId, java.lang.CharSequence targetType, java.lang.CharSequence targetId, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void deleteIgnore(java.lang.CharSequence userId, java.lang.CharSequence targetType, java.lang.CharSequence targetId, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void getIgnoreList(java.lang.CharSequence user_id, java.lang.CharSequence target_type, int page, int count, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void getExistsIgnore(java.lang.CharSequence userId, java.lang.CharSequence targetType, java.lang.CharSequence targetId, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}