/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.server.service.platform;

@SuppressWarnings("all")
public interface Setting {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Setting\",\"namespace\":\"com.borqs.server.service.platform\",\"types\":[{\"type\":\"error\",\"name\":\"ResponseError\",\"namespace\":\"com.borqs.server.base\",\"fields\":[{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"set\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"values\",\"type\":\"bytes\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"gets\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"keys\",\"type\":\"string\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getsByStartsWith\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"startsWith\",\"type\":\"string\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getDefault\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"}],\"response\":\"string\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getByUsers\":{\"request\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"users\",\"type\":\"string\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]}}}");
  boolean set(java.lang.CharSequence userId, java.nio.ByteBuffer values) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer gets(java.lang.CharSequence userId, java.lang.CharSequence keys) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getsByStartsWith(java.lang.CharSequence userId, java.lang.CharSequence startsWith) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.lang.CharSequence getDefault(java.lang.CharSequence userId, java.lang.CharSequence key) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getByUsers(java.lang.CharSequence key, java.lang.CharSequence users) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;

  @SuppressWarnings("all")
  public interface Callback extends Setting {
    public static final org.apache.avro.Protocol PROTOCOL = com.borqs.server.service.platform.Setting.PROTOCOL;
    void set(java.lang.CharSequence userId, java.nio.ByteBuffer values, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void gets(java.lang.CharSequence userId, java.lang.CharSequence keys, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void getsByStartsWith(java.lang.CharSequence userId, java.lang.CharSequence startsWith, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void getDefault(java.lang.CharSequence userId, java.lang.CharSequence key, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void getByUsers(java.lang.CharSequence key, java.lang.CharSequence users, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
  }
}