/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.server.service.platform;

@SuppressWarnings("all")
public interface StaticFile {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"StaticFile\",\"namespace\":\"com.borqs.server.service.platform\",\"types\":[{\"type\":\"error\",\"name\":\"ResponseError\",\"namespace\":\"com.borqs.server.base\",\"fields\":[{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"saveStaticFile\":{\"request\":[{\"name\":\"staticFile\",\"type\":\"bytes\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getStaticFile\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"asc\",\"type\":\"boolean\"},{\"name\":\"page\",\"type\":\"int\"},{\"name\":\"count\",\"type\":\"int\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getStaticFileById\":{\"request\":[{\"name\":\"file_id\",\"type\":\"string\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"deleteStaticFile\":{\"request\":[{\"name\":\"file_ids\",\"type\":\"string\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]}}}");
  boolean saveStaticFile(java.nio.ByteBuffer staticFile) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getStaticFile(java.lang.CharSequence userId, boolean asc, int page, int count) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getStaticFileById(java.lang.CharSequence file_id) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  boolean deleteStaticFile(java.lang.CharSequence file_ids) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;

  @SuppressWarnings("all")
  public interface Callback extends StaticFile {
    public static final org.apache.avro.Protocol PROTOCOL = com.borqs.server.service.platform.StaticFile.PROTOCOL;
    void saveStaticFile(java.nio.ByteBuffer staticFile, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void getStaticFile(java.lang.CharSequence userId, boolean asc, int page, int count, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void getStaticFileById(java.lang.CharSequence file_id, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void deleteStaticFile(java.lang.CharSequence file_ids, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}