/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.server.service.platform;

@SuppressWarnings("all")
public interface UserConfigration {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserConfigration\",\"namespace\":\"com.borqs.server.service.platform\",\"types\":[{\"type\":\"error\",\"name\":\"ResponseError\",\"namespace\":\"com.borqs.server.base\",\"fields\":[{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"saveConfigration\":{\"request\":[{\"name\":\"configration\",\"type\":\"bytes\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getConfigration\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"version_code\",\"type\":\"int\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"deleteConfigration\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"version_code\",\"type\":\"int\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getUserConfigration\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]}}}");
  boolean saveConfigration(java.nio.ByteBuffer configration) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getConfigration(java.lang.CharSequence userId, java.lang.CharSequence key, int version_code) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  boolean deleteConfigration(java.lang.CharSequence userId, java.lang.CharSequence key, int version_code) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getUserConfigration(java.lang.CharSequence userId) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;

  @SuppressWarnings("all")
  public interface Callback extends UserConfigration {
    public static final org.apache.avro.Protocol PROTOCOL = com.borqs.server.service.platform.UserConfigration.PROTOCOL;
    void saveConfigration(java.nio.ByteBuffer configration, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void getConfigration(java.lang.CharSequence userId, java.lang.CharSequence key, int version_code, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void deleteConfigration(java.lang.CharSequence userId, java.lang.CharSequence key, int version_code, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void getUserConfigration(java.lang.CharSequence userId, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
  }
}