/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.borqs.server.service.platform;

@SuppressWarnings("all")
public interface Video {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Video\",\"namespace\":\"com.borqs.server.service.platform\",\"types\":[{\"type\":\"error\",\"name\":\"ResponseError\",\"namespace\":\"com.borqs.server.base\",\"fields\":[{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"message\",\"type\":\"string\"}]}],\"messages\":{\"saveVideo\":{\"request\":[{\"name\":\"video\",\"type\":\"bytes\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getVideo\":{\"request\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"asc\",\"type\":\"boolean\"},{\"name\":\"page\",\"type\":\"int\"},{\"name\":\"count\",\"type\":\"int\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"getVideoById\":{\"request\":[{\"name\":\"video_id\",\"type\":\"string\"}],\"response\":\"bytes\",\"errors\":[\"com.borqs.server.base.ResponseError\"]},\"deleteVideo\":{\"request\":[{\"name\":\"video_ids\",\"type\":\"string\"}],\"response\":\"boolean\",\"errors\":[\"com.borqs.server.base.ResponseError\"]}}}");
  boolean saveVideo(java.nio.ByteBuffer video) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getVideo(java.lang.CharSequence userId, boolean asc, int page, int count) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  java.nio.ByteBuffer getVideoById(java.lang.CharSequence video_id) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;
  boolean deleteVideo(java.lang.CharSequence video_ids) throws org.apache.avro.AvroRemoteException, com.borqs.server.base.ResponseError;

  @SuppressWarnings("all")
  public interface Callback extends Video {
    public static final org.apache.avro.Protocol PROTOCOL = com.borqs.server.service.platform.Video.PROTOCOL;
    void saveVideo(java.nio.ByteBuffer video, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void getVideo(java.lang.CharSequence userId, boolean asc, int page, int count, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void getVideoById(java.lang.CharSequence video_id, org.apache.avro.ipc.Callback<java.nio.ByteBuffer> callback) throws java.io.IOException;
    void deleteVideo(java.lang.CharSequence video_ids, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}