
CREATE TABLE IF NOT EXISTS `audio` (
  `audio_id` BIGINT(20) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `summary` VARCHAR(4096) DEFAULT '',
  `description` VARCHAR(4096) DEFAULT '',
  `level` TINYINT(2) DEFAULT '0',
  `schools` VARCHAR(64) DEFAULT '0',
  `file_size` BIGINT(20) DEFAULT '0',
  `audio_time_length` BIGINT(20) DEFAULT '0',
  `audio_bit_rate` TINYINT(11) DEFAULT '0',
  `author` VARCHAR(64) DEFAULT '0',
  `audio_artists` VARCHAR(512) DEFAULT '',
  `record` VARCHAR(64) DEFAULT '0',
  `record_author` VARCHAR(64) DEFAULT '0',
  `record_year` VARCHAR(32) DEFAULT '0',
  `coding_type` VARCHAR(256) DEFAULT '',
  `compression_type` VARCHAR(256) DEFAULT '',
  `user_id` BIGINT(20) NOT NULL,
  `exp_name` VARCHAR(32) NOT NULL DEFAULT '',
  `html_url` VARCHAR(512) DEFAULT '',
  `content_type` VARCHAR(32) DEFAULT '',
  `new_file_name` VARCHAR(128) DEFAULT '',
  `created_time` BIGINT(20) NOT NULL DEFAULT '0',
  `updated_time` BIGINT(20) NOT NULL DEFAULT '0',
  `destroyed_time` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`audio_id`,`user_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8