document.write("<header>");
        document.write("<div class=\"navbar navbar-fixed-top\">");
            document.write("<div class=\"navbar-inner\">");
                document.write("<div class=\"container-fluid\">");
                    document.write("<a class=\"brand\" href=\"products_list.htm\"><i class=\"icon-home icon-white\"></i> Borqs Market <span class=\"sml_t\">1.0</span></a>");
                    document.write("<ul class=\"nav user_menu pull-right\">");
                    /*
                        document.write("<li class=\"divider-vertical hidden-phone hidden-tablet\"></li>");
                        document.write("<li class=\"dropdown\">");
                            document.write("<a href=\"#\" class=\"dropdown-toggle nav_condensed\" data-toggle=\"dropdown\"><i class=\"flag-gb\"></i> <b class=\"caret\"></b></a>");
                            document.write("<ul class=\"dropdown-menu\">");
                                document.write("<li><a href=\"javascript:void(0)\"><i class=\"flag-de\"></i> Deutsch</a></li>");
                                document.write("<li><a href=\"javascript:void(0)\"><i class=\"flag-fr\"></i> Français</a></li>");
                                document.write("<li><a href=\"javascript:void(0)\"><i class=\"flag-es\"></i> Español</a></li>");
                                document.write("<li><a href=\"javascript:void(0)\"><i class=\"flag-ru\"></i> Pусский</a></li>");
                            document.write("</ul>");
                        document.write("</li>");
                        */
                        document.write("<li class=\"divider-vertical hidden-phone hidden-tablet\"></li>");
                        document.write("<li class=\"dropdown\">");
                            document.write("<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><img src=\""+jquerySetCookie("market_user_img")+"\" alt=\"\" class=\"user_avatar\" />"+jquerySetCookie("market_display_name")+" <b class=\"caret\"></b></a>");
                            document.write("<ul class=\"dropdown-menu\">");
                                document.write("<li><a href=\"javascript:void(0)\">Setting</a></li>");
                                document.write("<li class=\"divider\"></li>");
                                document.write("<li><a href=\"http://bpc.borqs.com/login.html\">Log Out</a></li>");
                            document.write("</ul>");
                        document.write("</li>");
                    document.write("</ul>");
                    /*
                    document.write("<ul class=\"nav\" id=\"mobile-nav\">");
                        document.write("<li class=\"dropdown\">");
                            document.write("<a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><i class=\"icon-list-alt icon-white\"></i> Management <b class=\"caret\"></b></a>");
                            document.write("<ul class=\"dropdown-menu\">");
                                document.write("<li><a href=\"javascript:void(0)\">xxxxx</a></li>");
                                document.write("<li><a href=\"javascript:void(0)\">xxxx</a></li>");
                                document.write("<li><a href=\"javascript:void(0)\">xxxxx</a></li>");
                            document.write("</ul>");
                        document.write("</li>");
                        document.write("<li class=\"dropdown\">");
                           document.write(" <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><i class=\"icon-th icon-white\"></i> Statistics <b class=\"caret\"></b></a>");
                           document.write(" <ul class=\"dropdown-menu\">");
                              document.write("  <li><a href=\"javascript:void(0)\">Daily Report(TODO)</a></li>");
                               document.write(" <li><a href=\"javascript:void(0)\">Weekly Report(TODO)</a></li>");
                               document.write(" <li><a href=\"javascript:void(0)\">Month Report(TODO)</a></li>");
                           document.write(" </ul>");
                        document.write("</li>");
                       document.write(" <li class=\"dropdown\">");
                            document.write("<a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><i class=\"icon-wrench icon-white\"></i> Profile <b class=\"caret\"></b></a>");
                           document.write(" <ul class=\"dropdown-menu\">");
                                document.write("<li><a href=\"javascript:void(0)\">Update Profile(TODO)</a></li>");
                            document.write("</ul>");
                        document.write("</li>");
                        document.write("<li>");
                        document.write("</li>");
                    document.write("</ul>");
                    */
                document.write("</div>");
            document.write("</div>");
        document.write("</div>");
    document.write("</header>");